### ISSUE TITLE
Config option for prefix and/or suffix for fields conflicting with Go keywords

### ISSUE THREAD

**Issue by mikeschinkel** [ufukty/gonfique#2]
[Reference from Reddit](https://www.reddit.com/r/golang/comments/1aeu6zz/comment/kom4toj/?utm_source=reddit&utm_medium=web2x&context=3):

> "YAML file can not have Go keywords as keys, eg. type: user"

Rather than disallow Go keywords, how about giving users a configuration option for an optional prefix and/or suffix for that fields that conflict?

For example:

    prefix: X
    suffix: _

**Comment by ufukty** [comment]
My concern about requiring `gonfique` directives to be in user config is that the growth of directive set in time may lead to cluttered config files. Users usually wants their config to be concise as possible, for both readability and interoperability. Also they may think the tool pollutes their config files.

One possible solution to organize all gonfique directives under its name like (since it is unique and won't collide with any tool else)

```yaml
User:
  gonfique:
    prefix: "" 
    suffix: ""
    name: "" # specify the name of the generated type, instead above
``

Is there a concern about automatic caps convertion to TitleCase to avoid collisions with Go keywords?

**Comment by mikeschinkel** [comment]
> _"Users usually wants their config to be concise as possible, for both readability and interoperability."_

Any chance that is your [consensus bias](https://en.wikipedia.org/wiki/False_consensus_effect) talking?

My preference — which admittedly is a data point of one — is that I want my config to provide me as much functionality as possible, especially for those things I want to configure. And the more configuration options there are, the more likely the configuration I want will be available.

> _Also they may think the tool pollutes their config files._

What config files are you talking about?  I was assuming that you would have _(something like)_ a `~/.config/gonfique.yaml` and a `gonfique.yaml` per repo, and I can't imagine you'd have so many options that it would become difficult.

> _`name: "" # specify the name of the generated type, instead above`_

Seeing your comments on the other issue I started thinking that ideally you would have configuration that allowed a user to specify what to name their types to override whatever you chose.  The point about a prefix and suffix would be a simple, global to `gonfique` or global to a repo, so it would be trivial to manage for the user.

> _"Is there a concern about automatic caps convertion to TitleCase to avoid collisions with Go keywords?"_

Maybe I misunderstood your point.  When I read that I thought _"That won't address single words"_ but now that you are asking me I realize that was a brain fart and that Go keywords are lowercase.

Still, I assume you mean that if I have a property in YAML named `type` you are suggesting that TitleCase would be generating it as `Type`?

That actually brings up another concern, and that is that `type` is private in Go and `Type` is public, so I really think those considerations should be orthogonal to finding a way to avoid clashes with Go keywords.

In Go because of how reflection works all JSON marshalling needs to be to public properties, so I just assumed everything you were doing would be public properties.  But since you are generating code, that may or may not apply in your tool's case?

**Comment by ufukty** [comment]
About consensus bias; it is the unique biases and strong beliefs that what gives us courage to take a split from crowd and explore uncharted territories. Which I would not mind to show and sometimes I be proud of from having it, I believe I don't currently show it in this specific matter. 😶 Let me share a piece of what a well-structured k8s config looks like, so we can meet on same page about the subject. (I've asked ChatGPT to generate that so I'm not sure if there is any mistake in keywords.)

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: my-namespace

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
  namespace: my-namespace
data:
  my-key: my-value

---

apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: my-namespace
type: Opaque
data:
  password: MWYyZDFlMmU2N2Rm

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: my-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: my-image
        ports:
        - containerPort: 80
        env:
        - name: MY_KEY
          valueFrom:
            configMapKeyRef:
              name: my-config
              key: my-key
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: my-secret
              key: password

---

apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: my-namespace
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

```

I believe asking future adopters to insert gonfique specific directives on existing config code like above may backlash. Since some config files are already cluttered as is, even when they just focused on one-tool's logic.

Suggested approach will expose underlying problems to user. As prefixing with `X` will require user to use `XapiVersion.xkind.xmetadata.xname` kind of access pattern. Correct me if I've misinterpreted the advice.

Transforming to the TitleCase creates foreseeable behavior user gonna write their config file like above, but access like `ApiVersion.Kind.Metedata.Name`. About the access specifier concerns, I am not aware any usecase that piece/level/depth of config needs to be private for outsiders.

I will open another issue to have the naming collisions under records with more generalized form.

Thanks for your thorough post.

**Comment by mikeschinkel** [comment]
> _I believe asking future adopters to insert gonfique specific directives on existing config code like above may backlash. Since some config files are already cluttered as is, even when they just focused on one-tool's logic._

Ah, okay, I see now what the disconnect was. To paraphrase a quote attributed to many: 

> _"The biggest problem with communication is the assumption that it occurred.”_  

Clearly, it did not occur!  I was assuming one thing, and you meant another.

It never even occurred to me that to envision putting `gonfique`-specific directives in source `YAML` files, and I concur, almost certainly nobody would want that.

Explicitly stated, I think the source YAML must be independent and issolated from 

Instead, I envisioned only — as my prior comment made explicit — `gonfique`-specific config file like a `~/.config/gonfique.yaml` and a `gonfique.yaml` per repo.  

> [_"I don't consider an option where gonfique asks user a separate yaml file; as they can get out-of-sync to easily."_](https://github.com/ufukty/gonfique/issues/1#issuecomment-1925264260)

But you seem to be rejecting `gonfique`-specific config file, which I find unfortunate as I wouldn't see then getting out-of-sync to be a problem at all.  But then we may also be envisioning significantly different use-cases?

Currently I am working on a project where I use [three (3) separate generators](https://github.com/mikeschinkel/gerardus/blob/07cc797960f70c80e4acd44a9d35532beaddfff2/persister/ddl.go#L7-L10) where the output of each is implicitly the input of the next.

`sqlc` has its own configuration file, [`sqlc.yaml`](https://github.com/mikeschinkel/gerardus/blob/07cc797960f70c80e4acd44a9d35532beaddfff2/persister/sqlc.yaml), and I set its configuration once and have never since had a problem with it. 

What is your use-case where are going to run into problems?  Are you generating code during execution of your app on the user's machine, compiling on the user's machine, and then running it?  Because if it is just for use by the developer I don't see why having a `gonfique.yaml` could be problematic?

> [_"Providing users a flag to direct gonfique to always create isolated struct definitions (instead inline definitions) is easy to implement."_](https://github.com/ufukty/gonfique/issues/1#issuecomment-1925264260)

Both flags and config files are external to the source `YAML`, so both could just as easily get out-of-sync.  Which, while theoretically a problem, I have not found to be a problem in practice.

Suggested approach will expose underlying problems to user. As prefixing with X will require user to use XapiVersion.xkind.xmetadata.xname kind of access pattern. Correct me if I've misinterpreted the advice.

Suggested approach will expose underlying problems to user. As prefixing with X will require user to use XapiVersion.xkind.xmetadata.xname kind of access pattern. Correct me if I've misinterpreted the advice.

Transforming to the TitleCase creates foreseeable behavior user gonna write their config file like above, but access like ApiVersion.Kind.Metedata.Name. About the access specifier concerns, I am not aware any usecase that piece/level/depth of config needs to be private for outsiders.

I will open another issue to have the naming collisions under records with more generalized form.

Thanks for your thorough post.

**Comment by mikeschinkel** [comment]
I wanted to mention something else, probably that should be created in another issue but I'll either let you do that or direct me in what you would consider doing and then I'll do it.

Looking specifically at the K8s manifests you posted, I'm going to use one of them to illustrate my concern:

```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: my-namespace
type: Opaque
data:
  password: MWYyZDFlMmU2N2Rm
```

Not sure what `gonfique` would generate for this, but if I were to hand code it I would want it to generate the following:

```go
package K8sObjects

type Kind struct{
	Name string
}

type Namespace struct{
	Name string
}

type SecretType string

const (
	OpaqueType SecretType = "Opaque"
)

type MetaData struct {
	Name string
	Namespace *Namespace
}

type Secret struct {
	ApiVersion string
	Kind       *Kind
	Metadata *MetaData
	Type SecretType
	Data *SecretData
}

type SecretData struct{
	Password string
}
```
**Clearly**, to generate that from the `YAML` would require a lot of out-of-band configuration. 

Here is a configuration for that which I quickly mocked up, which I am sure would need to be significantly reworked to be usable. But obviously this type of config could not be fully encoded via command line flags without being wildly unusable. And note, this example only specifies that which cannot be discerned directly from the source `YAML` file:

```yaml
---
schemas:
    schema:
        name: Secret  
        match: 
            - .kind: Secret
        types:
            - .kind 
                - type: struct
                # Struct from string defaults to one property: `.Name`
            - .type
                - name: SecretType
                - const: {{value}Type = "{value}"  
                # `type: string` is assumed for single value properties in string format
            - .metadata 
                - name: \*MetaData
                # `type: struct` is assumed for dictionaries
            - .data 
                - name: \*SecretData
                # `type: struct` is assumed for dictionaries
```
  
You may look at this and say:

> _"What's the point?  That requires too much configuration; I just want to point at the YAML and be done with it."_

If that is your response, I would argue:

1. Generating less than well-structured types will just simplify the easy part — writing types — and make the much more complex part — using types over the lifecycle of the app — even harder.

2. I see this _(type of)_ configuration being done once and then used many times, by many people.  For example, you could write `gonfique` and then others could create config for specific use-cases, like Kubernetes, and then host those configs in their own repo.  If that did transpire, you'd be spawning 3rd party developers for `gonfique`.

Also clearly, for this to be reusable you'd need more than just a `.config` config and a repo config; you'd also need the ability to import other config files into your repo config.  

If this resonates with you, I could copy this comment to a new issue.

#fwiw #jmtcw
