### ISSUE TITLE
Iterables/Dictionaries

### ISSUE THREAD

**Issue by ufukty** [ufukty/gonfique#3]
In an example config file below

```yaml
# config.yml
Github:
  Domain: github.com
  Gateways:
    Public:
      Path: /api/v1.0.0
      Services:
        Document:
          Path: document
          Endpoints:
            List: { Method: "GET", Path: "list/{root}" }
        Objectives:
          Path: tasks
          Endpoints:
            Create: { Method: "POST", Path: "task" }
        Tags:
          Path: tags
          Endpoints:
            Creation: { Method: "POST", Path: "" }
            Assign: { Method: "POST", Path: "assign" }
Gitlab:
  Domain: gitlab.com
```

`Github.Gateways`, `Github.Gateways.Public.Services` and `Github.Gateways.Public.Services.Tags.Endpoints` are all *not literally but semantically* lists. There could be contexts that iterating over items of those lists (whose types are hypothetically `[]Gateway`, `[]Service`, `[]Endpoint`)  inevitable; eg. a generic function that takes a list of `Endpoint`s and registers into router.

Considerations:
- List items in YAML files are not required to share same schema.
- Field names are not available to iterating over, since they only exist before compilation.
