### ISSUE TITLE
Enum field containing types are not considered as candidate in type substitution

### ISSUE THREAD

**Issue by ufukty** [ufukty/gonfique#4]
```yaml
...
Create: { Method: "GET", Path: "/post" }
Update: { Method: "PUT", Path: "/post/{id}" }
Delete: { Method: "DELETE", Path: "/post/{id}" }
```

```go
type Method int

const (
  GET = Method(iota)
  POST
  PATCH
  DELETE
  PUT
)

type Endpoint struct {
  Method Method `yaml:"Method"`
  Path   string `yaml:"Path"`
}
```

Considerations:
- Enums can be defined with a type other than the one in YAML (eg. `string` <> `int` above)
