### ISSUE TITLE
Allow for type mapping, and via a config file

### ISSUE THREAD

**Issue by mikeschinkel** [ufukty/gonfique#5]
_This issue copied from [comment on #2](https://github.com/ufukty/gonfique/issues/2#issuecomment-1925452643)._

----

Looking specifically at the K8s manifests you posted, I'm going to use one of them to illustrate my concern:

```yaml
---
apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  namespace: my-namespace
type: Opaque
data:
  password: MWYyZDFlMmU2N2Rm
```

Not sure what `gonfique` would generate for this, but if I were to hand code it I would want it to generate the following:

```go
package K8sObjects

type Kind struct{
	Name string
}

type Namespace struct{
	Name string
}

type SecretType string

const (
	OpaqueType SecretType = "Opaque"
)

type MetaData struct {
	Name string
	Namespace *Namespace
}

type Secret struct {
	ApiVersion string
	Kind       *Kind
	Metadata *MetaData
	Type SecretType
	Data *SecretData
}

type SecretData struct{
	Password string
}
```
**Clearly**, to generate that from the `YAML` would require a lot of out-of-band configuration. 

### Mapping
Here is a configuration for that which I quickly mocked up, which I am sure would need to be significantly reworked to be usable. But obviously this type of config could not be fully encoded via command line flags without being wildly unusable. And note, this example only specifies that which cannot be discerned directly from the source `YAML` file:

```yaml
---
schemas:
    schema:
        name: Secret  
        match: 
            - .kind: Secret
        types:
            - .kind 
                - type: struct
                # Struct from string defaults to one property: `.Name`
            - .type
                - name: SecretType
                - const: {{value}Type = "{value}"  
                # `type: string` is assumed for single value properties in string format
            - .metadata 
                - name: \*MetaData
                # `type: struct` is assumed for dictionaries
            - .data 
                - name: \*SecretData
                # `type: struct` is assumed for dictionaries
```
  
You may look at this and say:

> _"What's the point?  That requires too much configuration; I just want to point at the YAML and be done with it."_

If that is your response, I would argue:

1. Generating less than well-structured types will just simplify the easy part — writing types — and make the much more complex part — using types over the lifecycle of the app — even harder.

2. I see this _(type of)_ configuration being done once and then used many times, by many people.  For example, you could write `gonfique` and then others could create config for specific use-cases, like Kubernetes, and then host those configs in their own repo.  If that did transpire, you'd be spawning 3rd party developers for `gonfique`.

Also clearly, for this to be reusable you'd need more than just a `.config` config and a repo config; you'd also need the ability to import other config files into your repo config.

**Comment by ufukty** [comment]
It looks like some types can get "recognized" by the context (parents) while for others it is the set of properties (children).

Easiest implementation is sadly not very flexible enough for changing pathways. Although it create advantage to user too, as it is the most readable, least cluttered one.

```yaml
types:
   - config.github.domain.gateways.public.services.document: DocService
   - config.github.domain.gateways.public.services.objectives: ObjService
   - config.github.domain.gateways.public.services.endpoints: EPService
```
[Source](https://github.com/ufukty/gonfique/issues/1#issuecomment-1924847719)

The other syntax looks like a DSL in YAML file, which lacks linter support. It defeats the purpose of this tool to exist by requiring developers to write code in not-type-checked environment. Also, developers don't love learning DSLs. Other than that, it is flexible against altering schemas but cluttered to "debug" when things go wrong.

I like the `pathway: typename` approach. It is easy to implement and also simple to use.

**Comment by ufukty** [comment]
Wildcard support on pathways can drastically improve the flexibility for changing pathways.

```yaml
config.github.*.*.*.services.document: GithubDoc # one level at each *
config.gitlab.*.*.*.services.document: GitlabDoc 
config.**.objectives: ObjService                 # multi-level for **
```

I've also lost `types` key and bullets.

**Comment by mikeschinkel** [comment]
> _"Easiest implementation is sadly not very flexible enough for changing pathways. Although it create advantage to user too, as it is the most readable, least cluttered one."
> _"types:"_
> _"   - config.github.domain.gateways.public.services.document: DocService"_
> _"   - config.github.domain.gateways.public.services.objectives: ObjService"_
> _"   - config.github.domain.gateways.public.services.endpoints: EPService"_

BTW, the reason I chose to show the example in this way was to avoid the sparse matrix of a mirrored YAML structure. 

OTOH, this syntax gets to be overwhelming when every property needs to be mapped.

> _"Wildcard support on pathways can drastically improve the flexibility for changing pathways."_

Definitely. Had not thought of that, but I like it.

> _"The other syntax looks like a DSL in YAML file"_ 

I assume you are talking about the syntax proposed in my first post of this issue?

Assuming yes, I reject that is is like a DSL. **_This_** would be a DSL:

```
DEFINE SCHEMA secret 
	MATCHING .kind="Secret"
	WITH TYPES
		.kind AS struct,
		.type NAMED SecretType AS const="{{value}Type = \"{value}\"",
		.metadata NAMED *MetaData,
		.data NAMED *SecretData
```

Yes, it does contain the same information, but presented as a data file containing patterns to match, and not as a language.

> _"It defeats the purpose of this tool to exist by requiring developers to write code in not-type-checked environment."_

1. I do not see how it is any less type-checked than any alternative, and
2. `gonfique` could easily _"type-check"_ it by calling out properties not found in the YAML, calling out invalid syntax for types, and calling out invalid syntax for the `const` pattern.

> _"Also, developers don't love learning DSLs."_ 

While I agree with that assertion, I again argue that this is **not** a _"DSL"_, per se.  First, the data is really just the things that are obviously needed to map properties to types, and does not include a bunch of strange concepts. 

Further, `gonfique` could easily generate a starter config showing how all the defaults would be configured so that developers would not have to start from scratch and could easily see how things works.

The only thing even remotely obscure or difficult to understand is the `const` property and generating an example would resolve that.

BTW, the irony of you called it a DSL for YAML is that if that were true, then the same could be said for essentially every other use-case of YAML, and especially for Kubernetes. 😄

> _"Other than that, it is flexible against altering schemas but cluttered to "debug" when things go wrong."_

Not if `gonfique` were to provide verbose logging to the console, then it would be easy to see why things went wrong.

**Comment by ufukty** [comment]
**Work in progress**

I could not shipped the feature as I still need to finalize some design decisions on incorporating this feature to other optional features. But, I wanted to share the latest state related with user-provided mappings support, the way it produce type defs.

User provided example config file:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: my-namespace
type: Opaque
data:
  my-key: my-value
  password: cGFzc3dvcmQ=
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  rules:
    - host: myapp.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: my-service
                port:
                  number: 80
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: my-image
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: my-config
            - secretRef:
                name: my-secret
```

user provided example mapping file:

```yaml
apiVersion: ApiVersion
metadata.name: Name
spec.rules.[]: Rule
spec.rules.[].Http.Paths.[]: Path
spec.ports.[]: Port
spec.**.containers: SpecContainers
spec.**.containers.[]: SpecContainer
spec.**.containers.[].name: ContainerName
```

Produced file:

```go
package config

import (
  "fmt"
  "os"
  "gopkg.in/yaml.v3"
)

type (
  SpecContainers []SpecContainer
  ApiVersion     string
  Name           string
  Rule           struct {
    Host string `yaml:"host"`
    Http struct {
      Paths []struct {
        Backend struct {
          Service struct {
            Name string `yaml:"name"`
            Port struct {
              Number int `yaml:"number"`
            } `yaml:"port"`
          } `yaml:"service"`
        } `yaml:"backend"`
        Path     string `yaml:"path"`
        PathType string `yaml:"pathType"`
      } `yaml:"paths"`
    } `yaml:"http"`
  }
  Port struct {
    Port       int    `yaml:"port"`
    Protocol   string `yaml:"protocol"`
    TargetPort int    `yaml:"targetPort"`
  }
  ContainerName string
  SpecContainer struct {
    EnvFrom []struct {
      ConfigMapRef struct {
        Name string `yaml:"name"`
      } `yaml:"configMapRef"`
      SecretRef struct {
        Name string `yaml:"name"`
      } `yaml:"secretRef"`
    } `yaml:"envFrom"`
    Image string        `yaml:"image"`
    Name  ContainerName `yaml:"name"`
    Ports []struct {
      ContainerPort int `yaml:"containerPort"`
    } `yaml:"ports"`
  }
)
type Config struct {
  ApiVersion ApiVersion `yaml:"apiVersion"`
  Data       struct {
    MyKey    string `yaml:"my-key"`
    Password string `yaml:"password"`
  } `yaml:"data"`
  Kind     string `yaml:"kind"`
  Metadata struct {
    Name      Name   `yaml:"name"`
    Namespace string `yaml:"namespace"`
  } `yaml:"metadata"`
  Spec struct {
    Ports    []Port `yaml:"ports"`
    Replicas int    `yaml:"replicas"`
    Rules    []Rule `yaml:"rules"`
    Selector struct {
      MatchLabels struct {
        App string `yaml:"app"`
      } `yaml:"matchLabels"`
    } `yaml:"selector"`
    Template struct {
      Metadata struct {
        Labels struct {
          App string `yaml:"app"`
        } `yaml:"labels"`
      } `yaml:"metadata"`
      Spec struct {
        Containers SpecContainers `yaml:"containers"`
      } `yaml:"spec"`
    } `yaml:"template"`
  } `yaml:"spec"`
  Type string `yaml:"type"`
}

func ReadConfig(path string) (Config, error) {
  f, err := os.Open(path)
  if err != nil {
    return Config{}, fmt.Errorf("opening config file: %w", err)
  }
  cfg := Config{}
  err = yaml.NewDecoder(f).Decode(&cfg)
  if err != nil {
    return Config{}, fmt.Errorf("decoding config file: %w", err)
  }
  return cfg, nil
}
```

Supported symbols are:
- `[]` for naming the **item** type rather than slice/array type, 
- `*` for matching all the fields/keys in the level it placed, 
- `**` for matching all fields/keys in multiple levels.

One rule is that `*` and `**` can not be placed at the end. 

Note that wildcards can make a rule match with multiple substructures in the config file. In such case, gonfique will check schemas of those structures and return an error if they are not same.

In the example config above, all of below patterns would match the same structure:
- `spec.template.spec.containers`, 
- `spec.*.spec.containers`,
- `spec.*.*.containers`,
- `spec.**.containers`

I like the current file structure (or syntax) of mapping file, as it is very easy to learn and let's user define flexible, reusable mappings against changing schemas.
